language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r movie-webservice
  - mkdir -p deploy
  - mv movie-webservice.zip deploy/movie-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: syh-movie-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: syh24/Movie
      branch: master

notifications:
  email:
    recipients:
      - dhkd689612@gmail.com